#Data Immersion And Wrangling

## Project Overview
* This project focuses on data cleaning and prepation using a retail sales dataset.
* The main goal is to understand the dataset and make it ready for analysis.

## Objectives
* Understand dataset structure
* Identify missing values and duplicates
* Clean and format the data
* Prepare final dataset for anlaysis

## Dataset Information
* Dataset Name: Retail Sales Dataset
* Format: Excel(.xlsx)
* Contains sales and customer details

## Final Output
* Clean and structured dataset ready for analysis.

**Import Libraries**

In [38]:
import pandas as pd
import numpy as np

**Load Dataset**

In [39]:
df = pd.read_csv("retail_sales_dataset.csv")
df.head()

   Order_ID Transaction_Date Client_Name Product_Name   Location  Sales_Amount
0      1001       2025-01-01        Arun       Laptop    Chennai       50000.0
1      1002       2025-01-02       Divya       Mobile  Bangalore       30000.0
2      1003       2025-01-03        Ravi       Tablet  Hyderabad       25000.0
3      1004       2025-01-04       Priya   Headphones     Mumbai           NaN
4      1005       2025-01-05     Karthik     Keyboard      Delhi        3000.0

**Intial Data Inspection**

In [40]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          30 non-null     int64
 1   Transaction_Date  30 non-null     object
 2   Client_Name       30 non-null     object
 3   Product_Name      30 non-null     object
 4   Location          30 non-null     object
 5   Sales_Amount      28 non-null     float64
dtypes: float64(1), int64(1), object(4)
memory usage: 1.5+ KB

          Order_ID  Sales_Amount
count    30.000000  2.800000e+01
mean   1015.500000  4.303825e+06
std       8.803408  2.267433e+07
min    1001.000000  3.100000e+02
25%    1008.250000  3.200000e+03
50%    1015.500000  1.650000e+04
75%    1022.750000  2.825000e+04
max    1030.000000  1.200000e+08

**Fix Column Names**

In [41]:
df.columns=df.columns.str.upper()
df.columns

Index(['ORDER_ID', 'TRANSACTION_DATE', 'CLIENT_NAME', 'PRODUCT_NAME',
       'LOCATION', 'SALES_AMOUNT'],
      dtype='object')

**Check Missing Values**

In [42]:
df.isnull().sum()

ORDER_ID            0
TRANSACTION_DATE    0
CLIENT_NAME         0
PRODUCT_NAME        0
LOCATION            0
SALES_AMOUNT        2
dtype: int64

**Handling Missing Values**

In [43]:
df["SALES_AMOUNT"]=df["SALES_AMOUNT"].fillna(df["SALES_AMOUNT"].mean())
df["LOCATION"]=df["LOCATION"].fillna("unknown")

**Outlier Identification and Removal**

In [44]:
df.sort_values(by="SALES_AMOUNT",ascending=False).head()
df=df[df["SALES_AMOUNT"]<1000000]

**Check And Remove Duplicate Rows**

In [45]:
df.duplicated().sum()
df=df.drop_duplicates()

**Final Validation**

In [46]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 27 entries, 0 to 29
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDER_ID          27 non-null     int64
 1   TRANSACTION_DATE  27 non-null     object
 2   CLIENT_NAME       27 non-null     object
 3   PRODUCT_NAME      27 non-null     object
 4   LOCATION          27 non-null     object
 5   SALES_AMOUNT      27 non-null     float64
dtypes: float64(1), int64(1), object(4)
memory usage: 1.5+ KB

   ORDER_ID TRANSACTION_DATE CLIENT_NAME PRODUCT_NAME   LOCATION  SALES_AMOUNT
0      1001       2025-01-01        Arun       Laptop    Chennai       50000.0
1      1002       2025-01-02       Divya       Mobile  Bangalore       30000.0
2      1003       2025-01-03        Ravi       Tablet  Hyderabad       25000.0
4      1005       2025-01-05     Karthik     Keyboard      Delhi        3000.0
5      1006       2025-01-06       Meena        Mouse    Kolkata        3200.0

**Save Cleaned File**

In [47]:
df.to_excel("cleaned_retail_sales_dataset.xlsx",index=False)